apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: web
        image: {{ .Values.image.web }}
        ports:
        - containerPort: {{ .Values.ports.web }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: POSTGRES_PASSWORD
      - name: db
        image: {{ .Values.image.db }}
        ports:
        - containerPort: {{ .Values.ports.db }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.env.POSTGRES_PASSWORD }}
