apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
spec:
  selector:
    app: myweb
  type: NodePort
  ports:
    - port: {{ .Values.ports.web }}
      targetPort: {{ .Values.ports.web }}
      nodePort: {{ .Values.nodePorts.web }}
